name: Publish package

on:
  workflow_run:
    workflows: ['Create release']
    types: [completed]
    branches: [main]

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: yarn install
      - name: transpile typescript
        run: yarn build
      - name: Get current version
        id: current_version
        run: echo "version=$(node -e 'console.log(require(`./package.json`).version)')" >> $GITHUB_OUTPUT
      - name: Get latest version
        id: latest_version
        run: echo "version=$(npm dist-tag ls | cut -d ' ' -f 2 | xargs echo)" >> $GITHUB_OUTPUT
      - name: Publish package
        if: ${{ steps.current_version.outputs.version != steps.latest_version.outputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
